### ISSUE TITLE
Token works for version 1 of the api, but not for version 2

### ISSUE THREAD

**Issue by sbhoek** [AgroDataCube/website#5]
On the homepage of the AgroDataCube it is stated with reference to the use of tokens: "(same for v1 and v2)". From this I infer that if I want to upgrade from version 1 to version, I can continue to use the same token. However, when I sent the following simple URLs to the server:
https://agrodatacube.wur.nl/api/v1/rest/fields/1
https://agrodatacube.wur.nl/api/v2/rest/fields/1

it works for version 1, but not for version 2! The error message I got is: Unknown token or token exceeded limits. So, it seems that it is not the same!

**Comment by robknapen** [comment]
Hi,

If I run the request https://agrodatacube.wur.nl/api/v1/rest/fields/1 in my browser the response is:

```
{ "type" : "FeatureCollection" , "features" : [   { "type": "Feature" 
 , "geometry" :  {"type":"MultiPolygon","coordinates":[[[[58741.714,366623.592],[58809.42,366698.549],[58818.319,366644.543],[58741.714,366623.592]]]]}, "properties": { "fieldid" : 1,"year" : 2009,"crop_code" : "863","crop_name" : "Bos, zonder herplantplicht","grondgebruik" : "Bouwland","area" : 2161.786289275322,"perimeter" : 235.160784006486}}]}
```

For the request https://agrodatacube.wur.nl/api/v2/rest/fields/1 the response is:

```
{ "type" : "FeatureCollection"  ,"metadata" : [{ "column_name" : "area","description" : "Area of a geometry","units" : "m2"},{ "column_name" : "crop_code","description" : "Code for the crop as supplied by RVO"},{ "column_name" : "crop_name","description" : "Name of the crop as supplied by RVO. For AgroDataCube harmonized over different years."},{ "column_name" : "fieldid","description" : "Unique id of a parcel in the AgroDataCube unique per parcel per year"},{ "column_name" : "geom","description" : "The geometry of an object or intersection depending on the resource and the parameters"},{ "column_name" : "grondgebruik","description" : "Categorized landuse at the parcel"},{ "column_name" : "perimeter","description" : "Perimeter of geometry","units" : "m"}],"features" : [   { "type": "Feature" 
 , "geometry" :  {"type":"MultiPolygon","coordinates":[[[[58741.714,366623.592],[58809.42,366698.549],[58818.319,366644.543],[58741.714,366623.592]]]]}, "properties": { "fieldid" : 1,"perimeter" : 235.161,"year" : 2009,"area" : 2161.786,"crop_name" : "Bos, zonder herplantplicht","grondgebruik" : "Bouwland","crop_code" : "863"}}]}
```

So slightly more detailed information is returned, but it works in both cases.

**Comment by sbhoek** [comment]
Ok, I have requested a new token and it works with the new one! I suspect that the token I used so far had some information stored inside that is now stored in the database on the server.
